### ISSUE TITLE
API documentations

### ISSUE THREAD

**Issue by ds2010** [ds2010/pyStoNED#24]
The new pr #23  (Autodoc) works well locally but does not on the ReadTheDocs.  You can check the [`CNLS`](https://pystoned.readthedocs.io/en/latest/api/formulations/CNLS.html) API in the website generated by ReadTheDocs. It is empty. 
However, if we compile the sphinx locally using `make html`, the docstring will show in the HTML file. See the following screenshot.

![Screenshot from 2020-12-06 22-10-46](https://user-images.githubusercontent.com/57257137/101291234-ef933900-380f-11eb-968d-ab2f2ca24ae8.png)

I failed to fix it. Since the website is automatically generated by the ReadTheDocs, @JulianATA , could you please help me to fix it? Thanks in advance!

**Comment by JulianATA** [comment]
@ds2010 , this should have been fixed!
Here is the reason why it occurs. According to the building process of the documentation on the readthedocs, there are couple lines of WARNING:
```
WARNING: autodoc: failed to import module 'CNLS' from module 'pystoned'; the following exception was raised:
No module named 'pyomo'
WARNING: autodoc: failed to import module 'ICNLS' from module 'pystoned'; the following exception was raised:
No module named 'pyomo'
```
The missing of dependencies `pyomo`, `matplotlib`, and `pandas` in requirements.txt leads to failure of importing the modules CNLS and ICNLS.
Consequently, the contents of the documentation are blank.
I have added these missing dependencies and should fixed the problem.

Thanks!

**Comment by ds2010** [comment]
> @ds2010 , this should have been fixed!
> Here is the reason why it occurs. According to the building process of the documentation on the readthedocs, there are couple lines of WARNING:
> 
> ```
> WARNING: autodoc: failed to import module 'CNLS' from module 'pystoned'; the following exception was raised:
> No module named 'pyomo'
> WARNING: autodoc: failed to import module 'ICNLS' from module 'pystoned'; the following exception was raised:
> No module named 'pyomo'
> ```
> 
> The missing of dependencies `pyomo`, `matplotlib`, and `pandas` in requirements.txt leads to failure of importing the modules CNLS and ICNLS.
> Consequently, the contents of the documentation are blank.
> I have added these missing dependencies and should fixed the problem.
> 
> Thanks!

Yeah, It woks very well. Thnaks you.
