### ISSUE TITLE
CNLSG: return then error when using the local solver

### ISSUE THREAD

**Issue by ds2010** [ds2010/pyStoNED#28]
Hi @JulianATA, it seems that there is another bug in line 122 [CNLSG ](https://github.com/ds2010/pyStoNED/blob/master/pystoned/CNLSG.py#L122). I have used the CNLSG to estimate the multiplicative cost function using a local solver `MINOS`, but it returns the following error: 

` File "/home/dais2/anaconda3/lib/python3.8/site-packages/pystoned/CNLSG.py", line 122, in __convergence_test
    self.Active2[i, j] = - alpha[i] - np.sum(beta[i, :] * x[i, :]) + \
TypeError: bad operand type for unary -: 'NoneType'`. 

Interestingly, when I using the 'NEOS' to solve the same model, there is no error, and I can receive the final estimation results. 
Further, there is no problem when we estimate the additive production function using the local solver `MOSEK`.

Could you please help to check and fix it? Many thanks! For your convenience, please see the following example:

## Example
```python3
import numpy as np
import pandas as pd
from pystoned import CNLSG
from pystoned.constant import CET_MULT, FUN_COST, OPT_LOCAL, RTS_VRS


url='https://raw.githubusercontent.com/ds2010/pyStoNED/master/pystoned/data/electricityFirms.csv'
df = pd.read_csv(url, error_bad_lines=False)

# output
y = df['TOTEX']

# inputs
x1 = df['Energy']
x1 = np.asmatrix(x1).T
x2 = df['Length']
x2 = np.asmatrix(x2).T
x3 = df['Customers']
x3 = np.asmatrix(x3).T
x = np.concatenate((x1, x2, x3), axis=1)

model = CNLSG.CNLSG(y, x, z=None, cet=CET_MULT, fun=FUN_COST, rts=RTS_VRS)
model.optimize(OPT_LOCAL)

model.display_beta()
```

**Comment by JulianATA** [comment]
I see, figuring the problem out.

**Comment by JulianATA** [comment]
@ds2010, the reason is that the mosek solver does not support multiplicative model.
I remember that we have a discussion about this, 
the conclusion of it is to log the message "Estimating the multiplicative model will be available in near future."
Is there any suggested local solver for multiplicative models recently?

**Comment by JulianATA** [comment]
refere to [CNLS:line117](https://github.com/ds2010/pyStoNED/blob/1508f3834e6b8c761e2e6899ad995aa8c508d4ba/pystoned/CNLS.py#L117)
