### ISSUE TITLE
doc(Example): The list of the outdated examples

### ISSUE THREAD

**Issue by JulianATA** [ds2010/pyStoNED#34]
The document is vital for users as reference.
Here are some pages updated:
* Stochastic Nonparametric Envelopment of Data
    * Method of Moments
    * Quassi-likelihood estimation
    * Kernel deconvolution estimation
* Multiple Outputs (DDF Formulation)
    * CNLS with multiple outputs
    * CQR (CER) with multiple outputs
* Data Envelopment Analysis
    * Radial model: Input orientation
    * Radial model: Output orientation

Once the documents are updated, we can close this issue.

**Comment by ds2010** [comment]
solved!
