### ISSUE TITLE
StoNED and Plot2d/3d: can not plot the StoNED frontier

### ISSUE THREAD

**Issue by ds2010** [ds2010/pyStoNED#40]
Hi @JulianATA, I found we can not plot the StoNED frontier using the [plot](https://github.com/ds2010/pyStoNED/blob/master/pystoned/plot.py). It should be OK. Please check the following error.

```python3
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-14-cfd06442dd17> in <module>
      2 rd = StoNED.StoNED(model)
      3 model_new = rd.get_frontier(RED_MOM)
----> 4 plot2d(model_new, x_select=0, label_name="StoNED frontier", fig_name="stoned_2d")

C:\Anaconda3\lib\site-packages\pystoned\plot.py in plot2d(model, x_select, label_name, fig_name)
     15         fig_name (String, optional): The name of figure to save. Defaults to None.
     16     """
---> 17     x = np.array(model.x).T[x_select]
     18     y = np.array(model.y).T
     19     if y.ndim != 1:

AttributeError: 'numpy.ndarray' object has no attribute 'x'

```

I have tried to add the following line to [StoNED](https://github.com/ds2010/pyStoNED/blob/master/pystoned/StoNED.py).
https://github.com/ds2010/pyStoNED/blob/b673006ff8fe7152125f42702173f9ce49d1d83e/pystoned/StoNED.py#L17

But it still does not work. Could you please help to fix it? Many thanks in advance!

Sheng

**Comment by ds2010** [comment]
The [plot](https://github.com/ds2010/pyStoNED/blob/master/pystoned/plot.py) should support to plot the DEA frontier, the CQR /CER estimated function and so on. So, how to do that?

**Comment by JulianATA** [comment]
@ds2010 , the plot method have been designed to support frontier functions: CNLS/ CQER ...
I'll provide an example for CQER later.
The support for DEA/FDH can be added.

I'm curious about plot for StoNED.
The frontier function can be plot with examples in this [pr](https://github.com/ds2010/pyStoNED/pull/39).
So, what information do you want to show in plot for StoNED.

**Comment by ds2010** [comment]
> @ds2010 , the plot method have been designed to support frontier functions: CNLS/ CQER ...
> I'll provide an example for CQER later.
> The support for DEA/FDH can be added.
> 
> I'm curious about plot for StoNED.
> The frontier function can be plot with examples in this [pr](https://github.com/ds2010/pyStoNED/pull/39).
> So, what information do you want to show in plot for StoNED.

This [pr](https://github.com/ds2010/pyStoNED/pull/39) just supports the plot of the CNLS estimated function instead of the StoNED frontier. Please note that CNLS estimated function and StoNED frontier are two different things. See the following figure.
![image](https://user-images.githubusercontent.com/57257137/121732218-a4c5e700-cafa-11eb-9922-7e1ea0ce857b.png)
(Kuosmanen, T., & Kortelainen, M. (2012). Stochastic non-smooth envelopment of data: Semi-parametric frontier estimation subject to shape constraints. Journal of Productivity Analysis, 38, 11–28.)

Note further that the [StoNED](https://github.com/ds2010/pyStoNED/blob/master/pystoned/StoNED.py) module has provided the function `get_frontier(self, method=RED_MOM)` (which is the estimated StoNED frontier) that can be directly used in the [plot](https://github.com/ds2010/pyStoNED/blob/master/pystoned/plot.py) module (see Line 23 in plot.py).

**Comment by JulianATA** [comment]
Thanks for implementing plot support for StoNED.

Here is example of plot for CQR/CER
## CQR
```python
from pystoned import CQER
from pystoned.plot import plot2d
from pystoned.constant import CET_ADDI, FUN_PROD, OPT_LOCAL, RTS_VRS
from pystoned import dataset as dataset

# import the GHG example data
data = dataset.load_GHG_abatement_cost(x_select=['HRSN', 'CPNK', 'GHG'],
                                        y_select=['VALK'])

# calculate the quantile model
model = CQER.CQR(y=data.y, x=data.x, tau=0.5, z=None,
                                              cet=CET_ADDI,
                                              fun=FUN_PROD,
                                              rts=RTS_VRS)
model.optimize(OPT_LOCAL)
plot2d(model, x_select=0,label_name="CQR estimated function")
```

## CER
```python
# import packages
from pystoned import CQER
from pystoned.plot import plot2d
from pystoned.constant import CET_ADDI, FUN_PROD, OPT_LOCAL, RTS_VRS
from pystoned import dataset as dataset

# import the GHG example data
data = dataset.load_GHG_abatement_cost(x_select=['HRSN', 'CPNK', 'GHG'],
                                        y_select=['VALK'])

# calculate the expectile model
model = CQER.CER(y=data.y, x=data.x, tau=0.5, z=None,
                                              cet=CET_ADDI,
                                              fun=FUN_PROD,
                                              rts=RTS_VRS)
model.optimize(OPT_LOCAL)

plot2d(model, x_select=0,label_name="CQR estimated function")
```

We can actually use the `plot2d` function on any frontier model with only one restriction "having single y".
Also, `plot3d` is designed for any frontier model with 2 restriction "having single y" and "have 2 or more x".

**Comment by ds2010** [comment]
Thanks for the CQR/CER examples. Could you please give an example to illustrate the StoNED frontier (using the CNLS as the first-stage estimator)? Here is an example, but with some unknown errors (bugs).

```python
# import packages
from pystoned import CNLS, StoNED
from pystoned.plot import plot2d
from pystoned.constant import CET_ADDI, FUN_PROD, RTS_VRS, OPT_LOCAL, RED_MOM
from pystoned.dataset import load_Tim_Coelli_frontier

# import the data from Tim Coelli Frontier 4.1 
data = load_Tim_Coelli_frontier(x_select=['labour'], y_select=['output'])

# define and solve the CNLS model
model = CNLS.CNLS(y=data.y, x=data.x, z=None, cet = CET_ADDI, fun = FUN_PROD, rts = RTS_VRS)
model.optimize(OPT_LOCAL)

# Plot the estimated function
rd = StoNED.StoNED(model)
model_new = rd.get_frontier(RED_MOM)
plot2d(model_new, x_select=0, label_name="StoNED frontier", fig_name="stoned_2d")
```

**Comment by ds2010** [comment]
Thanks for the CQR/CER examples. Could you please give an example to illustrate the StoNED frontier (using the CNLS as the first-stage estimator)? Here is an example, but with some unknown errors (bugs). Is it possible to fix it?

```python
# import packages
from pystoned import CNLS, StoNED
from pystoned.plot import plot2d
from pystoned.constant import CET_ADDI, FUN_PROD, RTS_VRS, OPT_LOCAL, RED_MOM
from pystoned.dataset import load_Tim_Coelli_frontier

# import the data from Tim Coelli Frontier 4.1 
data = load_Tim_Coelli_frontier(x_select=['labour'], y_select=['output'])

# define and solve the CNLS model
model = CNLS.CNLS(y=data.y, x=data.x, z=None, cet = CET_ADDI, fun = FUN_PROD, rts = RTS_VRS)
model.optimize(OPT_LOCAL)

# Plot the estimated function
rd = StoNED.StoNED(model)
model_new = rd.get_frontier(RED_MOM)
plot2d(model_new, x_select=0, label_name="StoNED frontier", fig_name="stoned_2d")
```

**Comment by JulianATA** [comment]
This code works fine on my computer with slightly adjustment.
Note that the whole model should be passed to the plot function. 
Hence the parameter should be `rd`.
The `model_new` in your code may only contain the information of `frontier`.
```python
from pystoned import CNLS, StoNED
from pystoned.plot import plot2d
from pystoned.constant import CET_ADDI, FUN_PROD, RTS_VRS, OPT_LOCAL, RED_MOM
from pystoned.dataset import load_Tim_Coelli_frontier

# import the data from Tim Coelli Frontier 4.1 
data = load_Tim_Coelli_frontier(x_select=['labour'], y_select=['output'])

# define and solve the CNLS model
model = CNLS.CNLS(y=data.y, x=data.x, z=None, cet = CET_ADDI, fun = FUN_PROD, rts = RTS_VRS)
model.optimize(OPT_LOCAL)

# Plot the estimated function
rd = StoNED.StoNED(model)
plot2d(rd, x_select=0, label_name="StoNED frontier", fig_name="stoned_2d")
```
The implementation works fine!
However the plot2d function calls `get_frontier()` with no parameter. 
Hence the frontier in StoNED is always using Method of Moments.

**Comment by JulianATA** [comment]
The newest commit has implement parameter `method` for StoNED.
Here is the an example with `QLE`.
```python3
from pystoned import CNLS, StoNED
from pystoned.plot import plot2d
from pystoned.constant import CET_ADDI, FUN_PROD, RTS_VRS, OPT_LOCAL, RED_QLE
from pystoned.dataset import load_Tim_Coelli_frontier

# import the data from Tim Coelli Frontier 4.1 
data = load_Tim_Coelli_frontier(x_select=['labour'], y_select=['output'])

# define and solve the CNLS model
model = CNLS.CNLS(y=data.y, x=data.x, z=None, cet = CET_ADDI, fun = FUN_PROD, rts = RTS_VRS)
model.optimize(OPT_LOCAL)

# Plot the estimated function
rd = StoNED.StoNED(model)
plot2d(rd, x_select=0, label_name="StoNED frontier", fig_name="stoned_2d", method=RED_QLE)
```
For plotting other models, the parameter `method` can be omitted.

**Comment by ds2010** [comment]
Thanks!
