### ISSUE TITLE
Solver Binding Error

### ISSUE THREAD

**Issue by fmobrj** [ds2010/pyStoNED#41]
Hello. Great work. I have been looking for something like this for a while. 

I am trying to run some examples but I am facing some issues with bindings ro the solver. Error message: 

"No Python bindings available for <class 'pyomo.solvers.plugins.solvers.mosek_direct.MOSEKDirect'> solver plugin"

Any hints on how to solve this?

**Comment by ds2010** [comment]
Did you install the Mosek module and its license? The estimation of the additive models relies on the solver, e.g., Mosek. Please find more details in the [Install](https://pystoned.readthedocs.io/en/latest/install/index.html). After that, if you have further questions, please let me know.

**Comment by fmobrj** [comment]
Thanks. I will check the license out. I have already installed Mosek. I have another question: in Stata I work with exponential distribution SFA models. Is there anyway to deal with exponential distribution models?

**Comment by ds2010** [comment]
Note that, in the `StoNED` related models, we assume that the inefficiency term `u` has a positive mean and a constant finite variance, that is, `u` follows a half normal distribution. We further assume zero mean noise with a constant finite variable, that is, the noise term `v` follows a normal distribution. We, thus, decomposite the estimated residuals based on these assumptions.

If you want to deal with the exponential distribution models, you have to extend the `method of moments` or `quassi-likelihood estimation` approach in [StoNED](https://github.com/ds2010/pyStoNED/blob/master/pystoned/StoNED.py) module based on the exponential assumption.
